// <auto-generated />
namespace RealGadget.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Applychanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Applychanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201706031054376_Applychanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
